apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcbank-gateway-ingress
  namespace: arcbank
  annotations:

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    
    alb.ingress.kubernetes.io/actions.ssl-redirect: |
      {"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    
    alb.ingress.kubernetes.io/group.name: banca-ecosistema-shared-alb
    
  labels:
    app: gateway-server
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /arcbank
        pathType: Prefix
        backend:
          service:
            name: gateway-server
            port:
              number: 80
