name: "Terraform Infraestructura"

on:
  pull_request:
    branches:
      - main
      - developer
    types: [opened, synchronize, closed]

jobs:
  terraform-plan:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged == false
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    steps:
      - name: "1. Checkout Código"
        uses: actions/checkout@v4

      - name: "2. Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "3. Terraform Init"
        run: terraform init

      - name: "4. Terraform Plan"
        run: terraform plan

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    steps:
      - name: "1. Checkout Código (main branch)"
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "2. Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "3. Terraform Init"
        run: terraform init

      - name: "4. Terraform Plan"
        run: terraform plan

      - name: "5. Terraform Apply"
        run: terraform apply -auto-approve