name: "Terraform Apply (Manual)"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Escribe "APLICAR" para ejecutar terraform apply'
        required: true

jobs:
  terraform-apply:
    name: "Aplicar Cambios"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'APLICAR'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
