name: "Terraform Infraestructura"

on:
  pull_request:
    branches:
      - main
      - developer
    types: [opened, synchronize, closed]    
jobs:
  terraform:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    steps:
      - name: "1. Checkout CÃ³digo"
        uses: actions/checkout@v4

      - name: "2. Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "3. Terraform Init"
        run: terraform init

      - name: "4. Terraform Plan"
    
        run: terraform plan -lock=false

      - name: "5. Terraform Apply"
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve -lock=false