name: "Terraform Infraestructura"

on:
  pull_request:
    branches:
      - main
      - developer
    types: [opened, synchronize]

jobs:
  terraform-validate-and-apply:
    name: "Validar y Aplicar Terraform"
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -input=false

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
